# Generated by Django 3.0.5 on 2020-04-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200407_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user_email',
            field=models.EmailField(max_length=30),
        ),
    ]
